from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class NovaRepository(Protocol):
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def save_session(self, session: Any) -> None: ...
    async def get_session(self, session_id: str) -> dict | None: ...
    async def update_session_title(self, session_id: str, title: str) -> bool: ...
    async def set_session_workspace(self, session_id: str, workspace_dir: str | None) -> bool: ...
    async def delete_session(self, session_id: str) -> bool: ...
    async def get_all_sessions(self, limit: int = 50, agent_key: str | None = None) -> list[dict]: ...
    async def get_sessions_by_parent_id(self, parent_id: str, limit: int = 50) -> list[dict]: ...
    async def add_message(self, session_id: str, role: str, content: str, **kwargs: Any) -> Any: ...
    async def get_messages(self, session_id: str, msg_filter: Any = None) -> list[Any]: ...
    async def compress_messages(self, session_id: str, target_count: int = 50) -> None: ...
    async def mark_messages_compacted(self, session_id: str) -> None: ...
    async def mark_messages_compacted_by_ids(self, session_id: str, message_ids: list[str]) -> None: ...
    async def update_session_compacted_at(self, session_id: str, timestamp: int) -> None: ...
    async def update_message_content(self, message_id: str, content: str) -> None: ...
    async def delete_messages(self, session_id: str, message_ids: list[str]) -> int: ...
    async def list_agents(self) -> list[dict]: ...
    async def get_agent(self, key: str) -> dict | None: ...
    async def save_agent(self, agent: dict) -> None: ...
    async def get_child_agents(self, parent_key: str) -> list[dict]: ...
    async def get_agent_parents(self, child_key: str) -> list[str]: ...
    async def get_agent_children(self, parent_key: str) -> list[str]: ...
    async def set_agent_parents(self, child_key: str, parent_keys: list[str]) -> None: ...
    async def add_agent_parent(self, child_key: str, parent_key: str) -> None: ...
    async def remove_agent_parent(self, child_key: str, parent_key: str) -> None: ...
    async def delete_agent(self, key: str) -> bool: ...
    async def save_memory(self, record: Any) -> None: ...
    async def get_memory_by_key(self, key: str, scope: str, session_id: str | None = None) -> dict | None: ...
    async def list_memories(self, filters: Any) -> list[dict]: ...
    async def delete_memory_by_id(self, memory_id: str) -> int: ...
    async def delete_memories_by_session(self, session_id: str) -> int: ...
    async def list_memories_by_session(self, session_id: str) -> list[dict]: ...
    async def delete_memory_by_key(self, key: str, scope: str, session_id: str | None = None) -> int: ...


DataSourceProtocol = NovaRepository

__all__ = ["DataSourceProtocol", "NovaRepository"]
